/** Popular Hinge/Tinder-style profile prompts to answer. Users can also write a custom one. */
export const PROFILE_PROMPTS: string[] = [
  "Two truths and a lie",
  "The way to win me over is",
  "I'm weirdly attracted to",
  "My most controversial opinion is",
  "A shower thought I recently had",
  "Dating me is like",
  "Green flags I look for",
  "I go crazy for",
  "My simple pleasures",
  "We'll get along if",
  "I'll fall for you if",
  "My love language is",
  "Unusual skills",
  "Typical Sunday",
  "The key to my heart is",
  "Together we could",
  "I want someone who",
  "Best travel story",
  "My therapist would say I",
  "This year I really want to",
  "The hallmark of a good relationship is",
  "Give me travel tips for",
];
